### ISSUE TITLE
期待项目管理/时间管理的经验分享

### ISSUE THREAD

**Issue by lilimul** [qdaxb/become-a-programmer#1]
看完了目前的章节，了解到了一些以前自己根本接触不到，或者不会去考虑的角度。
很多时候会需要给需求排期，但是实际发现会有各类插入事项，有些时候的产出效率也没有预期的高，粗排究竟需要调研到什么程度再给出？ 有什么技巧可以保证任务拆分够细，又可以按时间执行好？ 
期待分享

**Comment by qdaxb** [comment]
后面会有“成为项目管理者”的章节，只是可能还要很久……
